MODEL:
  FEATURE_DIM: 18
  RESUME_EPOCH: 0
  NO_FEATURE_ONLY_RGB: False
  LOSS: "L1"
  USE_DEPTH: True
  USE_PC_NORM: False
  MUL_POINTNET: True
  UNET_LAYERS: [32, 64,180,450,450, 180,64,32,26]
  POINTNET_NPOINTS: [512, 80, 20, 8]
  POINTNET_RADIUS : [[0.02, 0.08], [0.08, 0.15], [0.15, 0.4], [0.4, 1.2]]
  NO_MODIFY: False 
  STATIC_MODE: True




INPUT:
  SIZE_TRAIN: [650,900]
  SIZE_TEST: [650,900]
  NEAR_FAR_SIZE: [[0.5, 8.5, 0.8]]
  USE_RGB: False
  RGB_MAP: False
  USE_DIR: "MAPS" 

DATASETS:
  TRAIN: ["/data/NFS/colmap_datasets/data26/format"]
  FRAME_NUM: [1]
  MASK: False
  SHIFT: 10
  MAXRATION: 0.4
  ROTATION: 5.0
  #Holes: ["/data/wmy/NR/sfs/sport1_sfs_rotation_2_21_3","/data/wmy/NR/sfs/sport2_sfs_5","/data/wmy/NR/sfs/sport3_sfs_tmpn_5","None","/data/wmy/NR/sfs/basketball_ps_sfs_5"]
  #RANDOM_NOISY: 0.0
  SKIP_STEP : [1] 
  IGNORE_FRAMES: [[]]


SOLVER:
  OPTIMIZER_NAME: "Adam"
  BASE_LR: 0.00009
  WEIGHT_DECAY: 0.0000001
  IMS_PER_BATCH: 5
  WARMUP_FACTOR: 0.333
  WARMUP_ITERS: 10
  WARMUP_METHOD: "linear"
  MAX_EPOCHS: 3200
  CHECKPOINT_PERIOD: 100

  START_ITERS: 300
  END_ITERS: 1500
  LR_SCALE: 0.2

  LOSS_WHOLE_IMAGE: True


TEST:
  IMS_PER_BATCH: 256

OUTPUT_DIR: "/data/NFS/wmy/training/data26_colmap"
